[build.environment]

[context.deploy-preview]
    command = "mv robots-disallow.txt ./static/robots.txt && npm i esbuild && node node_modules/puppeteer/install.js && npm run build:graphql && npm run build"

[context.branch-deploy]
    command = "mv robots-disallow.txt ./static/robots.txt && npm i esbuild && node node_modules/puppeteer/install.js && npm run build:graphql && npm run build"

[context.dev]
    command = "mv robots-disallow.txt ./static/robots.txt && npm i esbuild && node node_modules/puppeteer/install.js && npm run build:graphql && npm run build"

[context.production]
    command = "mv robots-allow.txt ./static/robots.txt && npm i esbuild && node node_modules/puppeteer/install.js && npm run build:graphql && npm run build"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "https://beta.drips.network/*"
  to = "https://drips.network/:splat"
  status = 301
